services:
  - type: web
    name: cinema-backend
    runtime: go
    plan: free
    rootDir: cinema-backend
    buildCommand: go build -o main cmd/api/main.go
    startCommand: ./main
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_T12oWvNRdecQ@ep-quiet-resonance-aoqe46jp.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: VNPAY_TMN_CODE
        value: TEST1234
      - key: VNPAY_HASH_SECRET
        value: TESTSECRET1234567890123456789012
      - key: VNPAY_ENDPOINT
        value: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      - key: VNPAY_RETURN_URL
        value: https://cinema-backend.onrender.com/api/payments/vnpay/return
      - key: VNPAY_ENVIRONMENT
        value: sandbox
    healthCheckPath: /api/health
    autoDeploy: true
