services:
  - type: web
    name: cinema-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        generateValue: true
      - key: VNPAY_TMN_CODE
        sync: false
      - key: VNPAY_HASH_SECRET
        sync: false
      - key: VNPAY_ENDPOINT
        value: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      - key: VNPAY_RETURN_URL
        value: https://cinema-backend-yc14.onrender.com/api/payments/vnpay/return
      - key: VNPAY_ENVIRONMENT
        value: sandbox
      - key: CLOUDINARY_URL
        sync: false
      - key: FRONTEND_URL
        value: https://booking-room-admin.vercel.app
      - key: APP_ENV
        value: production
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: FROM_EMAIL
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
